TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.15

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  sim_time: 1.7
  transform_tolerance: 0.2

  holonomic_robot: true
  latch_xy_goal_tolerance: true

  vx_samples: 8
  occdist_scale: 0.05

