programs:
  -
    name: localization
    commands:  
      #- roslaunch shakey_executable shakey_localize.launch pkg:=$(find shakey_original_world) \015
      - roslaunch shakey_executable shakey_localize.launch pkg:=/home/david/shakey/src/shakey_original_world\015
  -
    name: 2d-navigation
    commands:
      - roslaunch shakey_2dnav shakey_2dnav.launch\015
  -
    name: object-detection
    commands:
      - roslaunch shakey_object_recognition shakey_object_recognition.launch\015
  -
    name: action-server
    commands:
      - roslaunch shakey_actionlib shakey_actionserver.launch\015
  -
    name: planner
    commands:
      - roslaunch shakey_planning_server continual-planning-shakey.launch map_suffix:='shakey_original_world'
