programs:
  -
    name: localization
    commands:
      - roslaunch shakey_executable shakey_localize.launch pkg:=$(rospack find shakey_hall78)
  -
    name: 2d-navigation
    commands:
      - roslaunch shakey_2dnav shakey_2dnav.launch
  -
    name: object-detection
    commands:
      - roslaunch shakey_object_recognition shakey_object_recognition.launch
  -
    name: action-server
    commands:
      - roslaunch shakey_actionlib shakey_actionserver.launch
  -
    name: teleop
    commands:
      - roslaunch cmd_mux teleop_joystick.launch
  -
    name: planner
    commands:
      - roslaunch shakey_planning_server continual-planning-shakey.launch map_suffix:='shakey_hall78'
