programs:
  -
    name: localization
    commands:  
      - roslaunch shakey_executable shakey_localize.launch pkg:='$(find shakey_hanga_world)' \015
      # - roslaunch shakey_executable shakey_localize.launch pkg:=/home/david/shakey/src/shakey_hanga_world\15
  -
    name: 2d-navigation
    commands:
      - roslaunch shakey_2dnav shakey_2dnav.launch\15
  -
    name: object-detection
    commands:
      - roslaunch shakey_object_recognition shakey_object_recognition.launch\15
  -
    name: action-server
    commands:
      - roslaunch shakey_actionlib shakey_actionserver.launch\15
  -
    name: planner
    commands:
      - roslaunch shakey_planning_server continual-planning-shakey.launch map_suffix:='shakey_hanga_world'\15
  -
    name: cmd_mux
    commands:
      - roslaunch cmd_mux cmd_mux.launch\15
